'use client';

import { useLocale } from 'next-intl';
import Link from 'next/link';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

export default function FCRAPage() {
  const locale = useLocale();
  const isES = locale === 'es';

  return (
    <div className="min-h-screen bg-offwhite py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <Link
          href={`/${locale}`}
          className="inline-flex items-center gap-2 text-gold hover:text-gold-dark mb-6"
        >
          <ArrowLeft className="w-4 h-4" />
          {isES ? 'Volver al inicio' : 'Back to home'}
        </Link>

        <div className="bg-white rounded-3xl p-8 md:p-12 shadow-lg border border-gold/20">
          <div className="flex items-center gap-3 mb-2">
            <ShieldCheck className="w-8 h-8 text-gold" />
            <h1 className="text-3xl md:text-4xl font-bold text-black">
              {isES ? 'Divulgación FCRA' : 'FCRA Disclosure'}
            </h1>
          </div>
          <p className="text-sm text-graydark mb-8">
            {isES ? 'Última actualización: 31 de mayo de 2026' : 'Last updated: May 31, 2026'}
          </p>

          <div className="prose prose-sm max-w-none text-graydark space-y-6">
            <div className="bg-gold/10 border border-gold/30 rounded-2xl p-6">
              <p className="font-medium text-black">
                {isES
                  ? 'Tus derechos bajo el Fair Credit Reporting Act (FCRA) son fundamentales. Esta divulgación resume tus derechos más importantes como consumidor.'
                  : 'Your rights under the Fair Credit Reporting Act (FCRA) are fundamental. This disclosure summarizes your most important rights as a consumer.'}
              </p>
            </div>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                1. {isES ? 'Derecho a Saber qué Hay en tu Archivo' : 'Right to Know What is in Your File'}
              </h2>
              <p>
                {isES
                  ? 'Tienes derecho a solicitar y obtener todo lo que está en tu archivo en las agencias de reporte de crédito. Una vez al año puedes obtener tu reporte gratis en annualcreditreport.com.'
                  : 'You have the right to request and receive everything in your file at credit reporting agencies. Once per year you can get your report free at annualcreditreport.com.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                2. {isES ? 'Derecho a Disputar Información Inexacta' : 'Right to Dispute Inaccurate Information'}
              </h2>
              <p>
                {isES
                  ? 'Si identificas información inexacta o incompleta, tienes derecho a disputarla. La agencia debe investigar generalmente en 30 días.'
                  : 'If you identify inaccurate or incomplete information, you have the right to dispute it. The agency must generally investigate within 30 days.'}
              </p>
              <p className="mt-2">
                <strong className="text-black">FCRA § 611(a)(1)(A)</strong>{' '}
                {isES
                  ? 'establece este derecho explícitamente.'
                  : 'explicitly establishes this right.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                3. {isES ? 'Manual Investigation vs e-OSCAR' : 'Manual Investigation vs e-OSCAR'}
              </h2>
              <p>
                {isES
                  ? 'Tienes derecho a solicitar explícitamente que tu disputa sea procesada con investigación MANUAL, no a través del sistema automático e-OSCAR. Todas las cartas generadas por Credit Legacy AI incluyen esta solicitud.'
                  : 'You have the right to explicitly request that your dispute be processed with MANUAL investigation, not through the automated e-OSCAR system. All letters generated by Credit Legacy AI include this request.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                4. {isES ? 'Derecho a Información Correcta o Eliminada' : 'Right to Information Corrected or Removed'}
              </h2>
              <p>
                {isES
                  ? 'Información inexacta, incompleta o no verificable DEBE ser corregida o eliminada (generalmente en 30 días).'
                  : 'Inaccurate, incomplete or unverifiable information MUST be corrected or removed (generally within 30 days).'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                5. {isES ? 'Información Negativa Obsoleta' : 'Outdated Negative Information'}
              </h2>
              <p>
                {isES
                  ? 'En la mayoría de los casos, una agencia de reporte de crédito no puede reportar información negativa de más de 7 años, o bancarrotas de más de 10 años.'
                  : 'In most cases, a credit reporting agency cannot report negative information older than 7 years, or bankruptcies older than 10 years.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                6. {isES ? 'CPN: ILEGAL' : 'CPN: ILLEGAL'}
              </h2>
              <p>
                {isES
                  ? 'Usar un CPN (Credit Profile Number) en lugar de tu SSN es FRAUDE bajo la ley federal. Credit Legacy AI rechaza automáticamente cualquier intento de usar CPN para proteger a nuestros usuarios.'
                  : 'Using a CPN (Credit Profile Number) instead of your SSN is FRAUD under federal law. Credit Legacy AI automatically rejects any CPN attempts to protect our users.'}
              </p>
              <p className="mt-2">
                {isES
                  ? 'Si estás usando o considerando usar un CPN, detente. Es ilegal y puede resultar en cargos criminales.'
                  : 'If you are using or considering using a CPN, stop. It is illegal and can result in criminal charges.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-black mt-6 mb-3">
                7. {isES ? 'Más Información' : 'More Information'}
              </h2>
              <p>
                {isES ? 'Para más detalles sobre tus derechos FCRA, visita:' : 'For more details about your FCRA rights, visit:'}
              </p>
              <ul className="space-y-1 mt-2">
                <li>
                  •{' '}
                  <a
                    href="https://www.consumerfinance.gov"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-gold hover:underline"
                  >
                    Consumer Financial Protection Bureau (CFPB)
                  </a>
                </li>
                <li>
                  •{' '}
                  <a
                    href="https://www.ftc.gov"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-gold hover:underline"
                  >
                    Federal Trade Commission (FTC)
                  </a>
                </li>
                <li>
                  •{' '}
                  <a
                    href="https://www.annualcreditreport.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-gold hover:underline"
                  >
                    annualcreditreport.com
                  </a>{' '}
                  ({isES ? 'reporte gratis anual' : 'free annual report'})
                </li>
              </ul>
            </section>

            <div className="border-t border-gold/20 pt-6 mt-8 text-xs">
              <p>
                <strong className="text-black">
                  {isES ? 'Aviso importante:' : 'Important notice:'}
                </strong>{' '}
                {isES
                  ? 'Credit Legacy AI no es una firma de abogados ni provee asesoría legal. Para asesoría legal específica, consulta a un abogado licenciado en tu jurisdicción.'
                  : 'Credit Legacy AI is not a law firm and does not provide legal advice. For specific legal advice, consult a licensed attorney in your jurisdiction.'}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
